const ADMIN_API='https://afyqxqvflchgwbtmoogd.supabase.co/functions/v1/rapat-admin';
let adminToken=localStorage.getItem('rapatSuperadmin')||'';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const nice=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
function msg(id,text,good=false){$(id).innerHTML=text?`<div class="alert ${good?'success':''}">${esc(text)}</div>`:''}
async function adminApi(data){const r=await fetch(ADMIN_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});let j={};try{j=await r.json()}catch{}if(!r.ok||!j.ok)throw new Error(j.error||'Request failed');return j}
async function authApi(action,data={}){return adminApi({action,sessionToken:adminToken,...data})}

async function adminLogin(){try{const j=await adminApi({action:'login',email:$('adminEmail').value,pin:$('adminPin').value});adminToken=j.session.token;localStorage.setItem('rapatSuperadmin',adminToken);$('adminProfile').textContent=`${j.profile.name} · ${j.profile.email}`;$('adminLogin').classList.add('hidden');$('adminApp').classList.remove('hidden');await loadDashboard()}catch(e){msg('adminLoginMsg',e.message)}}
function adminLogout(){localStorage.removeItem('rapatSuperadmin');adminToken='';location.reload()}
function adminTab(name,b){document.querySelectorAll('.admin-nav .tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.querySelectorAll('.admin-view').forEach(x=>x.classList.remove('on'));$(`view-${name}`).classList.add('on');if(name==='dashboard')loadDashboard();if(name==='organizations')loadOrganizations();if(name==='events')loadEvents();if(name==='candidates')loadCandidates();if(name==='audit')loadAudit()}

async function loadDashboard(){try{const j=await authApi('dashboard');const s=j.stats;$('platformStats').innerHTML=[['Organizations',s.organizations],['Events',s.events],['Candidates',s.candidates],['Employers',s.employers],['Interviews',s.interviews],['Completed',s.completed],['Shortlisted',s.shortlisted],['Offers',s.offers]].map(x=>`<div class="admin-stat"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');const vals=[j.radar.communication,j.radar.career_role,j.radar.experience,j.radar.technical,j.radar.professionalism];drawRadar(vals);const labs=['Communication','Career & Role','Experience','Technical','Professionalism'];$('platformRadarScores').innerHTML=`<p class="muted">Based on ${j.radar.candidate_count} evaluated candidate${j.radar.candidate_count===1?'':'s'}.</p>`+vals.map((v,i)=>`<div style="display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #edf1f5"><span>${labs[i]}</span><b>${Number(v||0).toFixed(2)} / 5</b></div>`).join('')}catch(e){if(e.message.includes('access'))return adminLogout();$('platformStats').innerHTML=`<div class="alert">${esc(e.message)}</div>`}}
function drawRadar(vals){const c=$('platformRadar'),x=c.getContext('2d'),cx=160,cy=150,R=100,n=5,labs=['Communication','Career & Role','Experience','Technical','Professionalism'];x.clearRect(0,0,320,300);x.font='11px Inter,Arial';for(let l=1;l<=5;l++){x.beginPath();for(let i=0;i<n;i++){const a=-Math.PI/2+i*2*Math.PI/n,r=R*l/5,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;i?x.lineTo(px,py):x.moveTo(px,py)}x.closePath();x.strokeStyle='#dce4ef';x.stroke()}for(let i=0;i<n;i++){const a=-Math.PI/2+i*2*Math.PI/n;x.beginPath();x.moveTo(cx,cy);x.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);x.strokeStyle='#dce4ef';x.stroke();const tx=cx+Math.cos(a)*(R+28),ty=cy+Math.sin(a)*(R+28);x.fillStyle='#607089';x.textAlign=tx<cx-5?'right':tx>cx+5?'left':'center';x.fillText(labs[i],tx,ty)}x.beginPath();vals.forEach((v,i)=>{const a=-Math.PI/2+i*2*Math.PI/n,r=R*Math.max(0,Math.min(5,Number(v||0)))/5,px=cx+Math.cos(a)*r,py=cy+Math.sin(a)*r;i?x.lineTo(px,py):x.moveTo(px,py)});x.closePath();x.fillStyle='rgba(36,88,220,.18)';x.fill();x.strokeStyle='#2458dc';x.lineWidth=2;x.stroke()}

async function loadOrganizations(){try{const j=await authApi('organizations');$('orgList').innerHTML=j.organizations.length?`<table class="admin-table"><thead><tr><th>Organization</th><th>Status</th><th>Events</th><th></th></tr></thead><tbody>${j.organizations.map(o=>`<tr><td><b>${esc(o.name)}</b></td><td>${esc(nice(o.status))}</td><td>${o.event_count}</td><td><button class="btn light small" onclick="toggleOrg('${o.id}','${o.status==='active'?'suspended':'active'}')">${o.status==='active'?'Suspend':'Activate'}</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No organizations yet.</div>';$('eventOrg').innerHTML=j.organizations.map(o=>`<option value="${o.id}">${esc(o.name)}</option>`).join('')}catch(e){$('orgList').innerHTML=`<div class="alert">${esc(e.message)}</div>`}}
async function createOrganization(){try{await authApi('create_organization',{name:$('newOrgName').value});$('newOrgName').value='';msg('orgMsg','Organization created.',true);await loadOrganizations()}catch(e){msg('orgMsg',e.message)}}
async function toggleOrg(id,status){try{await authApi('set_organization_status',{organizationId:id,status});await loadOrganizations()}catch(e){alert(e.message)}}

async function loadEvents(){try{const [ev,org]=await Promise.all([authApi('events'),authApi('organizations')]);$('eventOrg').innerHTML=org.organizations.map(o=>`<option value="${o.id}">${esc(o.name)}</option>`).join('');$('eventList').innerHTML=ev.events.length?ev.events.map(e=>{const orgName=Array.isArray(e.organizations)?e.organizations[0]?.name:e.organizations?.name;return `<div class="journey-card"><div class="sectiontitle"><div><h3 style="margin:0">${esc(e.name)}</h3><div class="muted2">${esc(e.slug)} · ${esc(orgName||'No organization')}</div></div><a class="btn light small" href="events-live.html?event=${encodeURIComponent(e.slug)}" target="_blank">Open Event</a></div><div class="detail-grid" style="margin-top:10px"><div class="detail-item"><small>Date</small>${esc(e.event_date||'-')}</div><div class="detail-item"><small>State / Venue</small>${esc([e.event_state,e.venue].filter(Boolean).join(' · ')||'-')}</div><div class="detail-item"><small>Status</small>${esc(nice(e.status))}</div><div class="detail-item"><small>Employers</small>${e.stats.employers}</div><div class="detail-item"><small>Vacancies</small>${e.stats.vacancies}</div><div class="detail-item"><small>Candidates</small>${e.stats.candidates}</div><div class="detail-item"><small>Interviews</small>${e.stats.interviews}</div><div class="detail-item"><small>Completed</small>${e.stats.completed}</div></div><div class="field"><label>Assign Organization</label><select onchange="assignEventOrg('${e.id}',this.value)">${org.organizations.map(o=>`<option value="${o.id}" ${o.id===e.organization_id?'selected':''}>${esc(o.name)}</option>`).join('')}</select></div></div>`}).join(''):'<div class="empty">No events yet.</div>'}catch(e){$('eventList').innerHTML=`<div class="alert">${esc(e.message)}</div>`}}
async function createEvent(){try{await authApi('create_event',{organizationId:$('eventOrg').value,name:$('newEventName').value,slug:$('newEventSlug').value,eventDate:$('newEventDate').value||null,eventState:$('newEventState').value,venue:$('newEventVenue').value,organizerName:$('newOrganizerName').value,organizerEmail:$('newOrganizerEmail').value,organizerPin:$('newOrganizerPin').value,status:'draft'});['newEventName','newEventSlug','newEventDate','newEventState','newEventVenue','newOrganizerEmail','newOrganizerPin'].forEach(id=>$(id).value='');msg('eventMsg','Event created.',true);await loadEvents()}catch(e){msg('eventMsg',e.message)}}
async function assignEventOrg(eventId,organizationId){try{await authApi('assign_event_organization',{eventId,organizationId})}catch(e){alert(e.message)}}

async function loadCandidates(){try{const j=await authApi('candidates',{q:$('candidateQuery').value});$('candidateList').innerHTML=j.candidates.length?`<div style="overflow:auto"><table class="admin-table"><thead><tr><th>Candidate</th><th>IC</th><th>Phone</th><th>Email</th><th>State / DUN</th><th>Event</th><th></th></tr></thead><tbody>${j.candidates.map(c=>{const ev=Array.isArray(c.events)?c.events[0]:c.events;return `<tr><td><b>${esc(c.full_name)}</b></td><td>${esc(c.ic)}</td><td>${esc(c.phone)}</td><td>${esc(c.email)}</td><td>${esc([c.state,c.dun].filter(Boolean).join(' · '))}</td><td>${esc(ev?.name||'-')}</td><td><button class="btn primary small" onclick="viewCandidate('${c.id}')">View Full Record</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No candidates found.</div>'}catch(e){$('candidateList').innerHTML=`<div class="alert">${esc(e.message)}</div>`}}
function evOf(x){return Array.isArray(x)?x[0]:x}
async function viewCandidate(id){try{const j=await authApi('candidate_detail',{candidateId:id}),c=j.candidate,base=c.canonical;let html=`<h2>${esc(base.full_name)}</h2><div class="detail-grid"><div class="detail-item"><small>IC</small>${esc(base.ic)}</div><div class="detail-item"><small>Phone</small>${esc(base.phone)}</div><div class="detail-item"><small>Email</small>${esc(base.email)}</div><div class="detail-item"><small>State</small>${esc(base.state||'-')}</div><div class="detail-item"><small>DUN</small>${esc(base.dun||'-')}</div><div class="detail-item"><small>Event Profiles</small>${c.profiles.length}</div></div><h3 style="margin-top:22px">Cross-Event Journey</h3>`;if(!c.applications.length)html+='<div class="empty">No interviews yet.</div>';else html+=c.applications.map(a=>{const event=evOf(a.events),v=evOf(a.vacancies),emp=evOf(v?.employers),e=evOf(a.evaluations)||{};const hasEval=Number(e.communication)>0;return `<div class="journey-card"><div class="sectiontitle"><div><b>${esc(event?.name||'Event')}</b><div class="muted2">${esc(v?.title||'-')} · ${esc(emp?.name||'-')} ${emp?.booth?'· Booth '+esc(emp.booth):''}</div></div><span class="badge ${a.status==='completed'?'ok':'wait'}">${esc(nice(a.status))}</span></div>${hasEval?`<div class="eval-grid"><div class="eval-score"><small>Communication</small><b>${e.communication}</b></div><div class="eval-score"><small>Career</small><b>${e.career_role}</b></div><div class="eval-score"><small>Experience</small><b>${e.experience}</b></div><div class="eval-score"><small>Technical</small><b>${e.technical}</b></div><div class="eval-score"><small>Professionalism</small><b>${e.professionalism}</b></div></div><p><b>Outcome:</b> ${esc(nice(e.outcome))} &nbsp; <b>Primary Gap:</b> ${esc(nice(e.primary_gap))}</p><p><b>Remarks:</b> ${esc(e.remarks||'-')}</p><p><b>Internal Note:</b> ${esc(e.internal_note||'-')}</p>`:'<p class="muted">No completed evaluation.</p>'}</div>`}).join('');$('candidateDetail').innerHTML=html;$('candidateDetailModal').classList.remove('hidden')}catch(e){alert(e.message)}}
function closeCandidateDetail(){$('candidateDetailModal').classList.add('hidden')}

async function loadAudit(){try{const j=await authApi('audit_log');$('auditList').innerHTML=j.logs.length?`<div style="overflow:auto;max-height:68vh"><table class="admin-table"><thead><tr><th>Time</th><th>Admin</th><th>Action</th><th>Entity</th><th>Metadata</th></tr></thead><tbody>${j.logs.map(l=>{const a=evOf(l.superadmins);return `<tr><td>${new Date(l.created_at).toLocaleString('en-MY')}</td><td>${esc(a?.name||'-')}</td><td>${esc(nice(l.action))}</td><td>${esc([l.entity_type,l.entity_id].filter(Boolean).join(' · '))}</td><td><code>${esc(JSON.stringify(l.metadata||{}))}</code></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No audit activity yet.</div>'}catch(e){$('auditList').innerHTML=`<div class="alert">${esc(e.message)}</div>`}}

(async()=>{if(adminToken){try{$('adminLogin').classList.add('hidden');$('adminApp').classList.remove('hidden');await loadDashboard()}catch{adminLogout()}}})();