const ORGANIZER_REPORT_API='https://afyqxqvflchgwbtmoogd.supabase.co/functions/v1/rapat-organizer-report';
window.openEval=function(raw){currentApp=JSON.parse(raw);scoreState={};$('evalCandidate').textContent=currentApp.candidates.full_name;$('evalJob').textContent=currentApp.vacancies.title;$('ratings').innerHTML=criteria.map(c=>`<div class="field"><label>${c.name}</label><div class="stars">${[1,2,3,4,5].map(n=>`<button type="button" class="scorebtn" id="s-${c.k}-${n}" onclick="setScore('${c.k}',${n})">${n}</button>`).join('')}</div></div>`).join('');$('evalOutcome').value='';$('evalGap').value='';$('evalRemarks').value='';$('evalNote').value='';msg('evalMsg','');$('evalModal').classList.remove('hidden')};
async function orgReport(){const r=await fetch(ORGANIZER_REPORT_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionToken})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Unable to load organizer data');return j}
function csvCell(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function evaluationOf(r){if(Array.isArray(r?.evaluations))return r.evaluations[0]||{};return r?.evaluations||{}}
function employerOf(r){const e=r?.vacancies?.employers;return Array.isArray(e)?(e[0]||{}):(e||{})}
window.downloadOrganizerData=async()=>{try{const j=await orgReport();const rows=[['Candidate','IC','Phone','Email','State','DUN','Employer','Booth','Vacancy','Status','Communication','Career & Role','Experience','Technical','Professionalism','Outcome','Primary Gap','Remarks','Internal Note']];j.rows.forEach(r=>{const e=evaluationOf(r),emp=employerOf(r);rows.push([r.candidates?.full_name||'',r.candidates?.ic||'',r.candidates?.phone||'',r.candidates?.email||'',r.candidates?.state||'',r.candidates?.dun||'',emp.name||'',emp.booth||'',r.vacancies?.title||'',r.status||'',e.communication??'',e.career_role??'',e.experience??'',e.technical??'',e.professionalism??'',e.outcome||'',e.primary_gap||'',e.remarks||'',e.internal_note||''])});const csv='\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n');const b=new Blob([csv],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`rapat-${slug}-all-data.csv`;a.click();URL.revokeObjectURL(u)}catch(e){alert(e.message)}};
window.viewOrganizerData=async()=>{try{const j=await orgReport();$('allDataBody').innerHTML=j.rows.length?j.rows.map(r=>{const e=evaluationOf(r),emp=employerOf(r);return `<tr><td>${esc(r.candidates?.full_name||'')}</td><td>${esc(emp.name||'')}</td><td>${esc(r.vacancies?.title||'')}</td><td>${e.communication??'-'}</td><td>${e.career_role??'-'}</td><td>${e.experience??'-'}</td><td>${e.technical??'-'}</td><td>${e.professionalism??'-'}</td><td>${esc(e.outcome||'-')}</td><td>${esc(e.primary_gap||'-')}</td><td>${esc(e.remarks||'-')}</td><td>${esc(e.internal_note||'-')}</td></tr>`}).join(''):'<tr><td colspan="12">No interview data yet.</td></tr>';$('allDataModal').classList.remove('hidden')}catch(e){alert(e.message)}};
window.closeAllData=()=>$('allDataModal').classList.add('hidden');
(function(){const tabs=document.querySelector('#organizer .tabs');if(tabs){const logout=[...tabs.querySelectorAll('button')].find(b=>b.textContent.trim()==='Logout');for(const [id,text,fn] of [['viewAllDataBtn','View All Data',viewOrganizerData],['downloadAllDataBtn','Download All Data',downloadOrganizerData]]){if(!document.getElementById(id)){const b=document.createElement('button');b.id=id;b.className='tab';b.textContent=text;b.onclick=fn;tabs.insertBefore(b,logout||null)}}}if(!document.getElementById('allDataModal')){const m=document.createElement('div');m.id='allDataModal';m.className='modal hidden';m.innerHTML='<div class="modalbox" style="max-width:1200px"><button class="close" onclick="closeAllData()">✕</button><div class="eyebrow">Organizer Data</div><h2>All Interview Data</h2><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr><th>Candidate</th><th>Employer</th><th>Vacancy</th><th>Comm.</th><th>Career</th><th>Exp.</th><th>Technical</th><th>Professional</th><th>Outcome</th><th>Primary Gap</th><th>Remarks</th><th>Internal Note</th></tr></thead><tbody id="allDataBody"></tbody></table></div></div>';document.body.appendChild(m);const s=document.createElement('style');s.textContent='#allDataModal th,#allDataModal td{padding:9px;border-bottom:1px solid #e7ebf1;text-align:left;white-space:nowrap}';document.head.appendChild(s)}})();